### PR TITLE
Fix bug with image deletion

### LINKED ISSUE #251: Deleting image deletes its base-image if they have the same name
- [x] Bug
- [ ] Feature
- [ ] Enhancement

## Detailed Description
```
$ dispatch create base-image nodejs vmware/dispatch-nodejs6-base:0.0.1-dev1 --language nodejs6
Created base image: nodejs

$ dispatch create image nodejs nodejs
Created image: nodejs

$ dispatch get image
   NAME  |                             URL                              | BASEIMAGE | STATUS |         CREATED DATE
------------------------------------------------------------------------------------------------------------------------
  nodejs | 10.7.252.23:5000/2793d16d-0862-448a-93e3-0faa7e6a6588:latest | nodejs    | READY  | Fri Dec 31 18:19:03 PST -0001

$ dispatch get base-image
   NAME  |                   URL                   | STATUS |         CREATED DATE
----------------------------------------------------------------------------------------
  nodejs | vmware/dispatch-nodejs6-base:0.0.1-dev1 | READY  | Fri Dec 31 18:18:55 PST -0001

$ dispatch delete image nodejs
Deleted image: nodejs

$ dispatch get base-image
  NAME | URL | STATUS | CREATED DATE
---------------------------------
```
With different names:
```
$ dispatch create base-image nodejs vmware/dispatch-nodejs6-base:0.0.1-dev1 --language nodejs6
Created base image: nodejs

$ dispatch create image node nodejs
Created image: node
$ dispatch get image
  NAME |                             URL                              | BASEIMAGE | STATUS |         CREATED DATE
----------------------------------------------------------------------------------------------------------------------
  node | 10.7.252.23:5000/7f99cc8d-d696-4e3a-8aac-34b4b8dd9be9:latest | nodejs    | READY  | Fri Dec 31 18:19:33 PST -0001

$ dispatch get base-image
   NAME  |                   URL                   | STATUS |         CREATED DATE
----------------------------------------------------------------------------------------
  nodejs | vmware/dispatch-nodejs6-base:0.0.1-dev1 | READY  | Fri Dec 31 18:19:20 PST -0001

$ dispatch delete image node
Deleted image: node

$ dispatch get base-image
   NAME  |                   URL                   | STATUS |         CREATED DATE
----------------------------------------------------------------------------------------
  nodejs | vmware/dispatch-nodejs6-base:0.0.1-dev1 | READY  | Fri Dec 31 18:19:20 PST -0001

$ dispatch get image
  NAME | URL | BASEIMAGE | STATUS | CREATED DATE
--------------------------------------------
```

## Complexity

- [x] Low - Simple enhancement or bug fix, no architectural changes or refactoring
- [ ] Medium - Change requires some thought, but is relatively isolated
- [ ] High - Significant architectural change or large refactor

## Impact

- [x] Low - Annoyance, but does not impact business or functinality
- [ ] Medium - Issue can be worked around, but is causing pain
- [ ] High - Blocker

### PR DESCRIPTION
**Pull request by rjew**
Fixes #251

### CODE REVIEW

File: pkg/image-manager/handlers.go [hunk 1]
```diff
@@ -539,15 +539,16 @@ func (h *Handlers) deleteImageByName(params image.DeleteImageByNameParams, princ
 				Message: swag.String("image not found"),
 			})
 	}
-	err = h.Store.Delete(ctx, params.XDispatchOrg, params.ImageName, &Image{})
+	e.Delete = true
+	_, err = h.Store.Update(ctx, e.Revision, &e)
```
Comment (berndtj) [inline pkg/image-manager/handlers.go]: Does the controller come around and actually delete the image?

Comment (rjew) [reply pkg/image-manager/handlers.go]: From what I checked it does. I tried logging out all the entities from the store and after calling update, it gets removed from the store. It looks like all our other resources get deleted by calling `update` instead of `delete`. When calling `delete` it throws an error.

File: pkg/image-manager/controller.go [hunk 2]
```diff
@@ -140,7 +140,7 @@ func (h *imageEntityHandler) Delete(ctx context.Context, obj entitystore.Entity)
 		log.Error(err)
 	}
 
-	var deleted BaseImage
+	var deleted Image
```
Comment (kars7e) [inline pkg/image-manager/controller.go]: Very interesting error. I was thinking how a unit test to cover this bug would look like and why is it even needed. If the store could have a concrete type, this error wouldn't have happened. I feel like generating a concrete store interfaces for each entity using https://github.com/google/gvisor/blob/master/tools/go_generics/generics.go could help us increase confidence in the code.

Comment (neosab) [reply pkg/image-manager/controller.go]: I kinda agree with having a concrete interface for storing entities to avoid such issues. Also, I realized this when I was trying to work with org entities which need to be stored and retrieved differently from other entities.
